### ISSUE TITLE
goland-eap-portable@2019.2-192.5728.72: download via aria2 failed

### ISSUE THREAD

**Issue by lpintes** [Ash258/Scoop-JetBrains#10]

**Comment by Ash258** [comment]
https://github.com/Ash258/Scoop-JetBrains/commit/37ccc1c03f4f12cf452d2e18792844431eb6f42e/checks#step:4:360

Yeah I cannot reproduce too.

![image](https://user-images.githubusercontent.com/13260377/63164502-ef729700-c028-11e9-94c1-93e32f7c93f9.png)

**Comment by lpintes** [comment]
Just for reference, here is console output, sorry I forgot to paste it when I opened this issue:
scoop install goland-eap-portable
WARN  Scoop uses 'aria2c' for multi-connection downloads.
WARN  Should it cause issues, run 'scoop config aria2-enabled false' to disable it.
Installing 'goland-eap-portable' (2019.2-192.5728.72) [64bit]
Starting download with aria2 ...
Download: [#b1da1f 0B/0B CN:1 DL:0B]
Download: [#b1da1f 0B/0B CN:1 DL:0B]
Download: [#b1da1f 0B/0B CN:1 DL:0B]
Download: [#b1da1f 0B/0B CN:1 DL:0B]
Download: 08/17 08:15:58 [ERROR] CUID#8 - Download aborted. URI=https://download.jetbrains.com/go/goland-192.5728.72.exe#/cosi.7z
Download: Exception: [AbstractCommand.cc:351] errorCode=19 URI=https://download.jetbrains.com/go/goland-192.5728.72.exe
Download:   -> [AbstractCommand.cc:792] errorCode=19 CUID#8 - Name resolution for download.jetbrains.com failed:Timeout while contacting DNS servers
Download: Download Results:
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: b1da1f|ERR |       0B/s|C:/Users/pintes/scoop/cache/goland-eap-portable#2019.2-192.5728.72#https_download.jetbrains.com_go_goland-192.5728.72.exe_cosi.7z
Download: Status Legend:
Download: (ERR):error occurred.
Download: aria2 will resume download if the transfer is restarted.
Download: If there are any errors, then see the log file. See '-l' option in help/man page for details.
ERROR Download failed! (Error 19) Name resolution failed
ERROR https://download.jetbrains.com/go/goland-192.5728.72.exe#/cosi.7z
    referer=https://download.jetbrains.com/go/goland-192.5728.72.exe#/
    dir=C:\Users\pintes\scoop\cache
    out=goland-eap-portable#2019.2-192.5728.72#https_download.jetbrains.com_go_goland-192.5728.72.exe_cosi.7z

ERROR & 'C:\Users\pintes\scoop\apps\aria2\current\aria2c.exe' --input-file='C:\Users\pintes\scoop\cache\goland-eap-portable.txt' --user-agent='Scoop/1.0 (+http://scoop.sh/) PowerShell/5.1 (Windows NT 10.0; Win64; x64; Desktop)' --allow-overwrite=true --auto-file-renaming=false --retry-wait=2 --split=5 --max-connection-per-server=5 --min-split-size=5M --console-log-level=warn --enable-color=false --no-conf=true --follow-metalink=true --metalink-preferred-protocol=https --min-tls-version=TLSv1.2 --stop-with-process=1136 --continue

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/Ash258/Scoop-JetBrains/issues/new?title=goland-eap-portable%402019.2-192.5728.72%3a+download+via+aria2+failed

It seems that aria2c doesn't work in this specific case, I disabled it and the download is progressing now.

**Comment by Ash258** [comment]
As I said. It is not issue. It is your local problem https://github.com/Ash258/Scoop-JetBrains/issues/10#issuecomment-521975919

`Download: -> [AbstractCommand.cc:792] errorCode=19 CUID#8 - Name resolution for download.jetbrains.com failed:Timeout while contacting DNS servers`

Your DNS have problems.
