### ISSUE TITLE
IntelliJ-IDEA-Ultimate-portable update is not reported by Scoop

### ISSUE THREAD

**Issue by xfournet** [Ash258/Scoop-JetBrains#11]
# Problem

Update from IntelliJ-IDEA-Ultimate-portable 2019.2-192.5728.98 to 2019.2.1-192.6262.58 is not reported by Scoop due to the way the versions are compared in Scoop that doesn't really support this versioning scheme.

Scoop status and update doesn't report the update, while scoop info show that the update is available
```
D:\scoop> scoop list
Installed apps:
  ....
  IntelliJ-IDEA-Ultimate-portable 2019.2-192.5728.98 [jetbrains]
  ....

D:\scoop> scoop status
Scoop is up to date.
Everything is ok!

D:\scoop> scoop info IntelliJ-IDEA-Ultimate-portable
Name: IntelliJ-IDEA-Ultimate-portable
Description: IntelliJ IDEA Ultimate. Cross-Platform Java IDE for professional developers by JetBrains.
Version: 2019.2-192.5728.98 (Update to 2019.2.1-192.6262.58 available)
Website: https://www.jetbrains.com/idea/
Manifest:
  D:\scoop\buckets\jetbrains\bucket\IntelliJ-IDEA-Ultimate-portable.json
Installed:
  D:\scoop\apps\IntelliJ-IDEA-Ultimate-portable\2019.2-192.5728.98
Binaries:
   IDE\bin\idea.bat IDE\bin\idea64.exe

D:\scoop> scoop update IntelliJ-IDEA-Ultimate-portable
IntelliJ-IDEA-Ultimate-portable: 2019.2-192.5728.98 (latest version)
Latest versions for all apps are installed! For more information try 'scoop status'
```

# Workaround

Use `-f` flag of the scoop update command
```
D:\scoop> scoop update -f IntelliJ-IDEA-Ultimate-portable
IntelliJ-IDEA-Ultimate-portable: 2019.2-192.5728.98 -> 2019.2.1-192.6262.58
WARN  Scoop uses 'aria2c' for multi-connection downloads.
WARN  Should it cause issues, run 'scoop config aria2-enabled false' to disable it.
Updating one outdated app:
Updating 'IntelliJ-IDEA-Ultimate-portable' (2019.2-192.5728.98 -> 2019.2.1-192.6262.58)
Downloading new version
Starting download with aria2 ...
....
```

The problem is caused by a mismatch between the versioning scheme used for this package and the way Scoop compare versions : the last digit of 2019.2.1 (ie 1) is compared to the first digit of 192.5728.98 (eg 192), see below
```
D:\scoop> . D:\scoop\apps\scoop\current\lib\versions.ps1
D:\scoop> compare_versions "2019.2.1-192.6262.58" "2019.2-192.5728.98"
-1
D:\scoop> compare_versions "2019.2.191-192.6262.58" "2019.2-192.5728.98"
-1
D:\scoop> compare_versions "2019.2.193-192.6262.58" "2019.2-192.5728.98"
1
```

# Possible fix

Either update the version scheme of this package
* always add a third digit to the version, eg use 2019.2.0-192.5728.98 instead of 2019.2-192.5728.98 `compare_versions "2019.2.1-192.6262.58" "2019.2.0-192.5728.98" => 1 `
* inverse the build number and the version number (but for the first update to the new scheme, there will be this problem again) : eg use 192.5728.98-2019.2 instead of 92.5728.98-2019.2 `compare_versions "192.6262.58-2019.2.1" "192.5728.98-2019.2" => 1`
* remove the build number of the version : eg 2019.2 instead of 2019.2-192.5728.98 `compare_versions "2019.2.1" "2019.2" => 1`

Either update the way Scoop compare versions, eg split the version by `-` and compare each sub-version one by one, based on `.` separator only. However this could break other Scoop package version scheme that rely on the current version comparison of Scoop ?
Eg in `scoop\lib\version.ps1`, replace functions `version` and `compare_versions` by
```
function version($ver) {
    $ver -split '[\.]' | ForEach-Object {
        $num = $_ -as [int]
        if($num) { $num } else { $_ }
    }
}
function compare_version_element($a, $b) {
    $ver_a = @(version $a)
    $ver_b = @(version $b)

    for($i=0;$i -lt $ver_a.length;$i++) {
        if($i -gt $ver_b.length) { return 1; }

        # don't try to compare int to string
        if($ver_b[$i] -is [string] -and $ver_a[$i] -isnot [string]) {
            $ver_a[$i] = "$($ver_a[$i])"
        }

        if($ver_a[$i] -gt $ver_b[$i]) { return 1; }
        if($ver_a[$i] -lt $ver_b[$i]) { return -1; }
    }
    if($ver_b.length -gt $ver_a.length) { return -1 }
    return 0
}
function compare_versions($a, $b) {
    $ver_a = @($a -split '[-]')
    $ver_b = @($b -split '[-]')

    for($i=0;$i -lt $ver_a.length;$i++) {
        if($i -gt $ver_b.length) { return 1; }

        $cmp = compare_version_element $ver_a[$i] $ver_b[$i]
        if($cmp -ne 0) {
            return $cmp
        }
    }
    if($ver_b.length -gt $ver_a.length) { return -1 }
    return 0
}
```

This make the IDEA version comparison works
```
D:\scoop> . D:\scoop\apps\scoop\current\lib\versions.ps1
D:\scoop> compare_versions "2019.2.1-192.6262.58" "2019.2-192.5728.98"
1
```

**Comment by Ash258** [comment]
lukesampson/scoop#3333 Fix is already in develop

**Comment by xfournet** [comment]
@Ash258  it look likes https://github.com/lukesampson/scoop/pull/3333 doesn't fix this problem:

```
D:\sources\github\scoop> git checkout develop
Switched to a new branch 'develop'
D:\sources\github\scoop> . .\lib\versions.ps1
D:\sources\github\scoop> Compare_Versions "2019.2.1-192.6262.58" "2019.2-192.5728.98"
-1
``` 
while it should 1.

Please advise if I should open a bug/PR into https://github.com/lukesampson/scoop ?

**Comment by xfournet** [comment]
@Ash258 it look likes that https://github.com/lukesampson/scoop/pull/3333 doesn't fix the problem regarding IDEA versions:

```
D:\sources\github\scoop> git checkout develop
D:\sources\github\scoop> . .\lib\versions.ps1
D:\sources\github\scoop> Compare-Version '2019.2.192-192.6262.58' '2019.2-192.5728.98'
-1
```
while it should return 1 to fix this issue.

Please advise if i should create a new issue/PR into https://github.com/lukesampson/scoop ?

**Comment by xfournet** [comment]
@Ash258  sorry, i just figured out that the new Compare-Version has not the same behaviour that the previous compare_versions function
 eg Compare-Version '2' '1' return -1 while compare_versions '2' '1' return 1
so it should be ok with the fix
