### ISSUE TITLE
Attaching Excavator updater

### ISSUE THREAD

**Issue by r15ch13** [Ash258/Scoop-JetBrains#2]
Hey, how about we let the [Excavator](https://github.com/r15ch13/Excavator) update this bucket and add it to [Scoops bucket list](https://github.com/lukesampson/scoop/blob/master/buckets.json)?
This way some redundant manifests from the extras bucket can get removed again.

- [dotPeek.json](https://github.com/lukesampson/scoop-extras/blob/master/bucket/dotPeek.json)
- [idea-eap.json](https://github.com/lukesampson/scoop-extras/blob/master/bucket/idea-eap.json)
- [idea-ultimate-eap.json](https://github.com/lukesampson/scoop-extras/blob/master/bucket/idea-ultimate-eap.json)
- [idea-ultimate.json](https://github.com/lukesampson/scoop-extras/blob/master/bucket/idea-ultimate.json)
- [idea.json](https://github.com/lukesampson/scoop-extras/blob/master/bucket/idea.json)
- [pycharm.json](https://github.com/lukesampson/scoop-extras/blob/master/bucket/pycharm.json)
- [webstorm.json](https://github.com/lukesampson/scoop-extras/blob/master/bucket/webstorm.json)

**Comment by Ash258** [comment]
Now i am handling updates on my local server in office using Scheduled jobs (Once a hour auto-pr with Push is executing), until i finally setup my server for wider usage (Ash258/Scoop-Ash258#13)

Feel free to add to bucket list and adopt extras bucket as needed.

**Comment by r15ch13** [comment]
Can we test the `Only bind new ssh key into project and use it for pushing` on your repo?
Adding only the public key would make it easier to add more repos to the Excavator without giving my whole GitHub account access to each one.

**Comment by r15ch13** [comment]
The public key would be: `ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC9D8JSDqGsQB4otkc084ue7gZKjwCr2/Sx49oAID8xM140sjLjGz8YYa6XW5CNBNA9Ja1qRdos4oMFvdzufevi0eK5fPrOVqsbt3zmsNICuWcKqxRDtdedgwaBV2Iv6EmVTOY18SZZktiNRr+QOuLA2Gcyffmkuz7hsGaJ9SBbtBYxBMLAybnSXjTKlnhjmDZrgfKr9q4WpS4qNMuWm6mQilwPoL431yUtU2z5pU7IuDnOT7PBZOYD3iOVwuhgV9wTSbnueiRTmejBXLNuJw4d2O3HE9gI9FhAuyokuSz0HqjOZUGktmbu/KsHteCqJ6k/g45XLMJ7svdJ9XfiBKqewe5sen5y83Xg2kdfeu66v3Tcp/L+7QjXK79AgYKBEEsN6H9jZh1kal1EGB0jCjkm6xrRJ7fj3Uo6xMYPWGe/m1JaU03vYcnBoKrMBKyVomMt92BAzYRGDqUtUn3eXivEgOBlI3LhY38/pCGCA5jiuxXDQsBy5gcAmlVz1UsKdsrfYaqikpfW7fDcwDIiahioGM/DVqKXwi7w4pYeF4MkpTI2IQ8y7i0Oqi86r9KGV0aSHA3TrN1AEk3EkqWuI2rRxpR/002+SG6+NS8BoM5OLHERGxvO21MklQ2/bP9OmKp2uelSEE1JF1XGAqWAOS/Rcbln/FomdeDjssl2r/0iIQ== Scoop-Excavator`

**Comment by Ash258** [comment]
I haven't tested it yet anywhere and only used this on gitlab, when i pushed as somone else with `git config --email ...` and it worked fine, unless that user have push access. I need to investigate if it's possible to add non github account as collaborator (so i could avoid creating separate Github user for update purpose).  If it will not be possible it's needed just to
1. Create New user (maybe even promote it to new level and use Github Apps 🤔)
1. Generate key
1. Add key to user
1. Add user as collaborator to all related repositories

**Comment by r15ch13** [comment]
https://developer.github.com/v3/guides/managing-deploy-keys/#deploy-keys
Hm, the deploy key stuff doesn't work... I guess. It's for single repos only.

**Comment by r15ch13** [comment]
For now, I need push privileges for this account, or should I let it use the pull-request method?

**Comment by Ash258** [comment]
Currenly updates are processed hourly and there is no need to adopt proper Excavator immediately using your server.

I will try to search for more suitable solution for wider today and i will get back to you in evening, what i have found so far.

**Comment by Ash258** [comment]
I think that deploy key method could work, not sure if on more repositories and how it will look in commit history, etc. 

Will you have spare time on tomorrow afternoon around (17:00 CET)? We could get in touch on gitter dms or something like that for faster response to test deploy key option.

Just to add new key, clone using ssh on your end and try to create new branch for example.

**Comment by Ash258** [comment]
Or this weekend. This week i have free weekend and will have time for this.

**Comment by r15ch13** [comment]
Yep, 17 CET is fine by me. :+1:

**Comment by r15ch13** [comment]
Rdy!

**Comment by Ash258** [comment]
Deeply sorry for such late response. My free weekend start on friday with call from one of my foreign customer with some critial issue so i had to drive there == no free weekend for me 😃

But i was thinking about it and it's not needed to bother you with these settings. I will keep my current update flow on my windows server until i finish my linux support servers. Then i test some options how to update just using ssh key and will inform you.

**Comment by r15ch13** [comment]
Okay :smile:

PS: I was playing `The Division 2` anyway :grin:

**Comment by Ash258** [comment]
Supressed by https://github.com/Ash258/scoop-GithubActions

987d1708667455a0dd7e23710b2f8b911aae6144 1b79e35566ff5a8f6388e29cf66bbd4f0e8cae3b
https://github.com/Ash258/Scoop-JetBrains/runs/157045942
