### ISSUE TITLE
IntelliJ-IDEA-portable@2020.1-201.6668.121: hash check failed

### ISSUE THREAD

**Issue by tianzhijiexian** [Ash258/Scoop-JetBrains#20]
Installing 'IntelliJ-IDEA-portable' (2020.1-201.6668.121) [64bit]
ideaIC-2020.1.win.zip (599.1 MB) [============================================================================] 100%
Checking hash of ideaIC-2020.1.win.zip ... ERROR Hash check failed!
App:         JetBrains/IntelliJ-IDEA-portable
URL:         https://download.jetbrains.com/idea/ideaIC-2020.1.win.zip
First bytes: 50 4B 03 04 0A 00 00 08
Expected:    db70d49d0c750c61d30007939026b5fdc3ddc713109678cd297ece6afbafca80
Actual:      a5460ba87513203855a862a8f9c1db967568e779b7a0ce9bb5fc98239f6b9b8b

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/Ash258/Scoop-JetBrains/issues/new?title=IntelliJ-IDEA-portable%402020.1-201.6668.121%3a+hash+check+fa
iled

**Comment by Ash258** [comment]
China specific issue. Use VPN
