### ISSUE TITLE
DataGrip-EAP is time to update : )

### ISSUE THREAD

**Issue by jiayaoO3O** [Ash258/Scoop-JetBrains#21]
The latest version is 2020.1.3

**Comment by Ash258** [comment]
...

The latest EAP (2020.03.26 version 201.6668.27) was before 1.3 GA release, which happened 14 days ago. 

https://data.services.jetbrains.com/products/releases?code=DG&latest=true&platform=zip&type=eap

As soon as there will be new EAP for next release it will be updated

**Comment by jiayaoO3O** [comment]
![image](https://user-images.githubusercontent.com/22891632/82010698-65358d00-96a5-11ea-906e-8fe347780d64.png)
But my DataGrip told me to download the latest version otherwise I can't use it

**Comment by Ash258** [comment]
That is how EAP works. EAP builds are expired after month (+-) after official full release.

There is no reason to use EAP when there is newer GA release.

**Comment by jiayaoO3O** [comment]
I understand that the EAP version will expire in 30 days, I mean,DataGrip now prompts me to download the new version, doesn't that mean there is already a new EAP version available? Shouldn't scoop be updated to the latest version to be consistent with its official website?
