### ISSUE TITLE
Resharper

### ISSUE THREAD

**Issue by JamieMagee** [Ash258/Scoop-JetBrains#22]
Is it possible to package resharper? Similar to dotMemory, dotPeek, etc.

**Comment by Ash258** [comment]
Resharer is not standalone IDE. 

It is visual studio extension which needs to be installed and have proper VS version

**Comment by JamieMagee** [comment]
Fair enough. I just found [this page](https://resharper-support.jetbrains.com/hc/en-us/articles/207241485-How-can-I-perform-a-silent-install-of-ReSharper-) which says it requires the `VsVersion` flag.

If not Resharper, is it possible to package the JetBrains Toolbox?

**Comment by Ash258** [comment]
https://scoop-docs.now.sh/apps/?query=jetbrains-toolbox

**Comment by JamieMagee** [comment]
🤦

Thanks!
