### ISSUE TITLE
Cannot update jetbrain products

### ISSUE THREAD

**Issue by nerdroid23** [Ash258/Scoop-JetBrains#28]
I have installed two jetbrains products via scoop, datagrip and phpstorm
They both have pending updates, when I try to update them via the console, this happens in both cases:
``` bash
PS C:\Users\$$$> scoop update phpstorm
phpstorm: 2020.2.3-202.7660.42 -> 2020.2.4-202.8194.11
Updating one outdated app:
Updating 'phpstorm' (2020.2.3-202.7660.42 -> 2020.2.4-202.8194.11)
Downloading new version
OperationStopped: C:\Users\nerdr\scoop\apps\scoop\current\lib\install.ps1:130
Line |
 130 |          throw $e
     |          ~~~~~~~~
     | The operation has timed out.
```

What could be causing this and what could be a fix or workaround? I do not have any knowledge of powershell scripts so I am not able to look into it.
And btw, other scoop apps install and update without any issues.

**Comment by Ash258** [comment]
![image](https://user-images.githubusercontent.com/13260377/100835496-07fcff80-346e-11eb-9640-b99c72aacc39.png)
