### ISSUE TITLE
lowercase manifest name

### ISSUE THREAD

**Issue by h404bi** [Ash258/Scoop-JetBrains#3]
I don't use this bucket, just advice to keep uniform with the core/extras buckets. But whatever, just like a vim2emacs war.

**Comment by Ash258** [comment]
There is no reason to use all lowercase. It's mess and it's not friendly. Naming in extras is mess, some use lowercase, some uppercase, ...

There are no official guidance on how to write and name manifest (each collaborator / contributor use own best practise how to write and mainatain manifests), so talking about "keeping uniform" is prety out of the box.

In my buckets i always use Pascal case wth dashes for spaces and this is something which is not gonna change.
