### ISSUE TITLE
Update DataGrip-portable

### ISSUE THREAD

**Issue by TheWiresharkGuy** [Ash258/Scoop-JetBrains#36]
```
PS > scoop info DataGrip-portable
```
Name: DataGrip-portable
Description: DataGrip. Cross-Platform IDE for Databases & SQL by JetBrains.
Version: 2021.1-211.6693.68 **(Update to 2021.1.1-211.7142.37 available)**
Website: https://www.jetbrains.com/datagrip/
License: Proprietary (https://www.jetbrains.com/store/license.html)
...

> Not sure if I should open an issue for this, sorry ...

**Comment by Ash258** [comment]
What does this mean??

Latest version is available at `2021.1.1-211.7142.37` 

![image](https://user-images.githubusercontent.com/13260377/120217850-3438e380-c239-11eb-90e2-5b66e0b3c921.png)

**Comment by TheWiresharkGuy** [comment]
Explanations:

`scoop update DataGrip-portable` does nothing ...

![image](https://user-images.githubusercontent.com/37513220/120463970-b55cbb80-c39c-11eb-8999-86936c5d0f7c.png)

`scoop update -f DataGrip-portable` does indeed update

Not sure if this is the intended behavior for portable apps ... ?

**Comment by TheWiresharkGuy** [comment]
Edit:

After migrating to shovel, no more problems, thanks!
