### ISSUE TITLE
persistedConfig => profile

### ISSUE THREAD

**Issue by Retia-Adolf** [Ash258/Scoop-JetBrains#4]
For example, change `installer` part for IntelliJ IDEA portable:
```
    "installer": {
        "script": [
            "$file = 'idea.properties'",
            "$ideHome = '${idea.home.path}'",
            "if (-not (Test-Path \"$persist_dir\\$file\")) {",
            "    Write-Host 'File' $file 'does not exists. Creating.' -f Yellow",
            "    $file = \"$dir\\bin\\$file\"",
            "    $CONT = Get-Content $file",
            "        # Replacing config options",
            "    $CONT = $CONT -replace '^# idea.config.path=.*$', \"idea.config.path=$ideHome/profile/config\"",
            "    $CONT = $CONT -replace '^# idea.system.path=.*$', \"idea.system.path=$ideHome/profile/system\"",
            "    $CONT = $CONT -replace '^# idea.plugins.path=', 'idea.plugins.path='",
            "    $CONT = $CONT -replace '^# idea.log.path=', 'idea.log.path='",
            "        # Rewrite properties file",
            "    Set-Content $file ($CONT -join \"`r`n\") -Encoding Ascii -Force",
            "}"
        ]
    },
```
1. `persistedConfig` is somewhat redundant, maybe we could change it to `profile`? as the term used in [here](https://www.jetbrains.com/help/idea/2018.3/tuning-the-ide.html#73a32237) or [here](https://intellij-support.jetbrains.com/hc/en-us/articles/207240985):

> * **user profile** drive runs out of space
> * default **user profile** points to the UNC path unsupported by the IDE
> * **user profile** directory is not detected correctly

2. In `idea.properties` file in Intellij IDEA, there says:

  > `# Use ${idea.home.path} macro to specify location relative to IDE installation home.`

  But others seem maybe slightly different from Intellij IDEA? (e.g. [RubyMine](https://www.jetbrains.com/help/ruby/2018.3/file-idea-properties.html)):

  >  Use ${idea.home} macro to specify location relative to IDE installation home.

**Comment by Ash258** [comment]
1. Maybe why not. There no advantage in any case. 
    - If i decide to change, i will make it personally.
    - PRs are welcome, but for this huge change I have to skip CI (internal agreement with appveyor due tu some CI settings) and will fix few other things
    - I still need to edit multiple manifests so i will change name to `profile` aswell
1. I rather use my custom created path since it's easy to create and straightforward, i don't want to rely on their internal variable (possible changes, differencies between applications)
This is just template, which will work in any JetBrains Application and you can just copy it to any app, so no need to struggle with some version changes / application dependeds. 

I read all changelogs for all applications, so i will be ready to change it when some problem occours.

**Comment by Retia-Adolf** [comment]
Okay, got it. Another problem: when there is a patch update, currently it will report error: `Failed to prepare an update: Temp directory inside installation`

If separating them into two dirs, for those already have current major release installed, they can get minor version update without downloading whole large package.

So maybe like this:
```json
    "extract_to": "ide",
    "installer": {
        "script": [
            "$newDir = \"$(Split-Path \"$dir\")\\current\" -replace '\\\\', '/'",
            "$file = 'idea.properties'",
            "if (-not (Test-Path \"$persist_dir\\bin\\$file\")) {",
            "    Write-Host 'File' $file 'does not exists. Creating.' -f Yellow",
            "    $file = \"$dir\\bin\\$file\"",
            "    $CONT = Get-Content $file",
            "    $profileDir = \"$newDir/profile\"",
            "        # Replacing config options",
            "    $CONT = $CONT -replace '^# idea.config.path=.*$', \"idea.config.path=$profileDir/config\"",
            "    $CONT = $CONT -replace '^# idea.system.path=.*$', \"idea.system.path=$profileDir/system\"",
            "    $CONT = $CONT -replace '^# idea.plugins.path=', 'idea.plugins.path='",
            "    $CONT = $CONT -replace '^# idea.log.path=', 'idea.log.path='",
            "        # Rewrite properties file",
            "    Set-Content $file ($CONT -join \"`r`n\") -Encoding Ascii -Force",
            "}"
        ]
    },
    "persist": [
        "ide\\bin\\idea.properties",
        "profile"
    ],
    "architecture": {
        "64bit": {
            "shortcuts": [
                [
                    "ide\\bin\\idea64.exe",
                    "IntelliJ IDEA Community (Early Access Program)"
                ]
            ]
        },
        "32bit": {
            "shortcuts": [
                [
                    "ide\\bin\\idea.exe",
                    "IntelliJ IDEA Community (Early Access Program)"
                ]
            ]
        }
    },
```
