### ISSUE TITLE
Add JetBrains DataSpell EAP

### ISSUE THREAD

**Issue by RaphaelTarita** [Ash258/Scoop-JetBrains#45]
The public EAP for JetBrains DataSpell (notebook software for `.ipynb`) just opened, and it would be nice to be able to install it via scoop. In a similar manner of how you can install EAPs and RCs of other JetBrains IDEs, there could be a `DataSpell-EAP` manifest.

Homepage of DataSpell: https://www.jetbrains.com/dataspell/

**Comment by Ash258** [comment]
Seriously?? 61a49b756e284feb3310d2d0e35c1bfe106a1c59

**Comment by RaphaelTarita** [comment]
Well, turns out this was a scoop bug. The jetbrains bucket didn't update properly, that's why I didn't have the manifest locally. I had to remove and re-add the bucket to get the new manifests.
