### ISSUE TITLE
[Feature Required] Provide "Open as XXX project" menu item, please?

### ISSUE THREAD

**Issue by Dragon1573** [Ash258/Scoop-JetBrains#47]
This issue is related to previously closed issue #45.

## Background of the request

[ScoopInstaller/Extras](https://github.com/ScoopInstaller/Extras) provided 2 *Windows Registy Manager* scripts for *Microsoft Visual Studio Code*. They looks like follows:

![image](https://user-images.githubusercontent.com/49941141/141128360-70753013-01fc-41c5-a29a-43dd564beef6.png)

The 2 `*.reg` provide (un)installation for "Open with Code" item in right-click menu:

![image](https://user-images.githubusercontent.com/49941141/141129069-8095fa36-60e0-402f-9a47-85cce7248eb4.png)

## My needs

Could @Ash258 provide similar `DataSpell-EAP-install-context.reg` & `DataSpell-EAP-uninstall-context.reg` (so other JetBrains IDEs) for us so we can enable the "Open folder as DataSpell (EAP) project" menu item on our own by running the `*.reg` scripts?

Thank you very much! ❤️

**Comment by Ash258** [comment]
No.

Until there is official support for such registry manipulations, I refuse to add and support flaky regedit scripts.

In Shovel it will be added as `--register-context-menu` (subject of change) option for installation in future version and for Windows11 only.

For scoop I cannot tell when they plan to integrate such features natively.
